AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120


# The following cops were added to RuboCop, but are not configured.
# Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.
# Please also note that you can opt-in to new cops by default by adding this to your config:
#
# AllCops: NewCops: enable
# Gemspec/AddRuntimeDependency: # new in 1.65 Enabled: true
# Gemspec/DeprecatedAttributeAssignment: # new in 1.30 Enabled: true
# Gemspec/DevelopmentDependencies: # new in 1.44 Enabled: true
# Gemspec/RequireMFA: # new in 1.23 Enabled: true
# Layout/LineContinuationLeadingSpace: # new in 1.31 Enabled: true
# Layout/LineContinuationSpacing: # new in 1.31 Enabled: true
# Layout/LineEndStringConcatenationIndentation: # new in 1.18 Enabled: true
# Layout/SpaceBeforeBrackets: # new in 1.7 Enabled: true
# Lint/AmbiguousAssignment: # new in 1.7 Enabled: true
# Lint/AmbiguousOperatorPrecedence: # new in 1.21 Enabled: true
# Lint/AmbiguousRange: # new in 1.19 Enabled: true
# Lint/ConstantOverwrittenInRescue: # new in 1.31 Enabled: tr...